### ISSUE TITLE
BUGS PARA GRUPO 9

### ISSUE THREAD

**Issue by JuanSanAri** [Proyectos1-FDI-UCM/c2324-Grupo10#82]
Buenas chicos del grupo9, os dejo el issue creado para que abajo escribáis bugs que vayáis viendo, un abrazo.

**Comment by OscarMelquiadesDuranNarganes** [comment]
En principio los bugs tenemos que añadirlos mediante issues que publiquemos nosotros, así que quizá no debamos usar este hilo y en su lugar crear nuestros propios.

**Comment by OscarMelquiadesDuranNarganes** [comment]
# El personaje no es visible al salir del nivel y comenzar de nuevo.
### Descripción
**Resultado ocurrido**:
Cuando el jugador usa el menú de pausa para salir del nivel, pulsar el botón de Jugar vuelve a cargar el nivel, pero el personaje no puede verse.
**Resultado esperado**:
Al salir al menú principal, pulsar el botón “Jugar” y comenzar el nivel nuevamente, con un personaje visible que controlar.

### Pasos
1. Pulsar el botón “Jugar” en el menú principal.
2. Tras aparecer en el nivel, pulsar la tecla Esc para entrar en el menú de pausa.
3. Pulsar el botón “Salir” en el menú de pausa.
4. Pulsar de nuevo el botón “Jugar” en el menú principal.
5. Error ocurrido: El personaje no aparece al entrar en el nivel. 

Sin embargo, este error puede ser arreglado por el usuario mediante los pasos siguientes:
1. En el nivel, pulsar de nuevo la tecla Esc para entrar en el menú de pausa.
2. Pulsar el botón “Continuar” en el menú de pausa.
3. El personaje cae del techo, y puede ser controlado de nuevo.

### Captura de pantalla
![Captura de pantalla (3903)](https://github.com/Proyectos1-FDI-UCM/c2324-Grupo10/assets/149335285/ec22ce27-2d7e-4d31-aacd-a29a8f4e86b1)

**Comment by OscarMelquiadesDuranNarganes** [comment]
# Los ataques del Fauno no siguen la trayectoria deseada.
### Descripción
**Resultado ocurrido**:
De vez en cuando, el Fauno lanza un ataque que se queda en su lugar.
**Resultado esperado**: 
Todos los ataques del Fauno deberían seguir trayectorias similares en vez de permanecer estáticos.

### Pasos
1. Completar el tutorial y entrar en la pantalla de selección de nivel.
2. Entrar en el nivel del Fauno.
3. Permitir que el Fauno lance proyectiles periódicamente.
4. Error ocurrido: Algunos de los proyectiles se quedan en su lugar.


### Captura de vídeo
[Enlace a la grabación](https://youtu.be/IXwXob0ny60)

**Comment by OscarMelquiadesDuranNarganes** [comment]
# El personaje no entró en el estado de deslizamiento de pared.
### Descripción
**Resultado ocurrido**:
Al presionarse contra la pared, el personaje entró en el estado idle.
**Resultado esperado**: 
Al presionarse contra la pared, el personaje entraría en el estado de deslizamiento de pared..
### Pasos
No reproducible.

### Captura de pantalla o vídeo
[Enlace a la grabación](https://youtu.be/GipJI4QTWtg)

**Comment by OscarMelquiadesDuranNarganes** [comment]
# El personaje puede actuar brevemente tras morir.
### Descripción
**Resultado ocurrido**:
Cuando el personaje muere, el jugador aún es capaz de disparar el trabuco y moverse.
**Resultado esperado**: 
Cuando el personaje muere, el jugador pierde todo el control sobre él.
### Pasos
1. Entrar en cualquier nivel con amenazas dañinas como la sección de tutorial de walljump o las batallas de jefe.
2. Recibir suficiente daño como para disminuir la vida del jugador a 0.
3. Antes de que aparezca la pantalla de muerte, pulsar los botones de disparo y movimiento a discreción.
4. Error ocurrido: El personaje puede disparar y moverse aunque no tenga vida.
### Captura de pantalla o vídeo
[Enlace a la grabación](https://youtu.be/P2lTF7YXzos)

**Comment by IzanDeVegaLopez** [comment]
# Menú de Pausa permite seguir girando al personaje #
### Descripción ###
**Resultado obtenido**
Cuando el menú de pausa esta abierto mover al personaje no lo mueve pero cambia hacia donde mira.
**Resultado esperado**
Mientras el menú de pausa esté abierto el juego se pausa por completo, no dejando que ninguna animación se reproduzca ni se pueda ver ningún cambio.

### Pasos ###
1. Entrar en la escena del tutorial o en alguna de la de los jefes
2. Pulsar ESC para abrir el menú de pausa
3. Pulsar A o D (los botones de movimiento del personaje)
4. El personaje ha girado => Bug reproducido

**Comment by IzanDeVegaLopez** [comment]
# Problema joystick del mando #
### Descripción ###
**Resultado obtenido**
Con un mando el personaje solo se moverá a la izquierda si el valor
absoluto del joystick en el eje y es mayor al del eje X. Es decir que solo te deja ir a la
derecha si el joystick está colocado entre los puntos (-1,1)~(0,1) y (-1,-1)~(0,-1)
Considerando el (-1,0) el joystick a la izquierda del todo.
En otras palabras el personaje solo se mueve hacia la izquierda si el joystick esta a la izquierda y arriba o a la izquierda y abajo (las dos diagonales de la izquierda)
**Resultado esperado**
El joystick te permite ir hacia la izquierda siempre que pulses hacia la
izquierda
### Pasos ###
1. Conecta un mando
2. Entrar en la escena del tutorial o en alguna de la de los jefes
3. Intentar moverse hacia la izquierda (probar distintos ángulos en el joystick) => Bug reproducido

**Comment by IzanDeVegaLopez** [comment]
# Problema direccionalidad del trabuco al jugar con mando #
### Descripción ###
**Resultado obtenido**
El trabuco no dispara arriba ni abajo al pulsar el joystick hacia abajo o
hacia arriba y disparar.
**Resultado esperado**
Al igual que con el teclado, al pulsar abajo o arriba y disparar que
dispare en esa dirección.
### Pasos ###
1. Conecta un mando
2. Entrar en la escena del tutorial o en alguna de la de los jefes
3. Pulsar el joystick hacia arriba
4. Disparar => Bug reproducido

**Comment by IzanDeVegaLopez** [comment]
# Sliders del menú de pausa bloqueados #
### Descripción ###
**Resultado obtenido**
Los sliders del menú de pausa están bloqueados y no se moverán
**Resultado esperado**
Los sliders del menú de pausa se pueden modificar con el ratón y estos cambian el volumen de la música y los efectos en consecuencia.
### Pasos ###
1. Entrar en la escena del tutorial o en alguna de la de los jefes
2. Pulsar ESC para abrir el menú de pausa
2. Clicar con el ratón en alguno de los sliders y deslizar el ratón hacia izquierda y derecha sin soltar el botón => Bug reproducido

**Comment by IzanDeVegaLopez** [comment]
# Proyectiles del fauno a veces no golpean #
### Descripción ###
**Resultado obtenido**
A veces los proyectiles del fauno te atravesarán sin hacerte daño
**Resultado esperado**
Al tocar un proyectil del fauno recibes daño
### Pasos ###
1. Entrar en la escena del tutorial, completarlo y avanzar hasta la escena del fauno
2. Esperar a que el fauno haga el patrón de disparar
3. No pasa todas las veces, y desconozco que sucede que hace que ocurra este bug. Pero si al entrar en la escena uno de los proyectiles te golpea el resto también lo hará, si no te golpea el resto tampoco lo hará.

**Comment by IzanDeVegaLopez** [comment]
# Bug bloquea el movimiento en el lobby#
### Descripción ###
**Resultado obtenido**
Al entrar en un portal de transición de zona con el disparo cargado activado dejamos de poder controlar a nuestro personaje al soltar el botón del ataque cargado. Es posible que también pase en la transición a escenas de jefes pero no lo he probado
**Resultado esperado**
El disparo cargado se cancela al entrar por uno de los portales, o bien conserva la carga y puede dispararla sin problemas.
### Pasos ###
1. Entrar en la escena del tutorial y abrir la última puerta
2. Antes de entrar a la siguiente zona cargar el disparo cargado
3. Atravesar el portal
4. Soltar el botón del disparo cargado (el personaje no dispara) => Bug reproducido

**Comment by IzanDeVegaLopez** [comment]
# Bug animaciones enemigos al morir durante algunos patrones #
### Descripción ###
**Resultado obtenido**
Al matar un boss durante un patrón la animación de muerte del boss se retrasará o no se mostrará. Pasa con la carrera del Fauno y la hypnosis de serpicol como poco
**Resultado esperado**
Al morir el jefe su patrón actual se detendrá junto a su animación 
### Pasos ###
1. Entrar en la escena del tutorial y completarla
2. Entrar a una de las escenas de jefe
3. Quitarle toda la vida cuando este en medio de un patrón => Bug reproducido

**Comment by IzanDeVegaLopez** [comment]
# Aceptar en los menús #
### Descripción ###
**Resultado obtenido**
Solo el ratón permite pulsar los botones del menú.
**Resultado esperado**
El botón A / B del mando o similar sirven para aceptar en los menús.
Para el teclado estaría bien que por ejemplo la tecla de disparo tuviese el mismo ejemplo o
alguna otra que esté a mano.
### Pasos ###
1. En el menú principal o en el menú de pausa de cualquier escena de combate
2. Intentar elegir pulsar o cambiar el botón seleccionado actualmente con teclas del teclado o con mando => Bug reproducido
